validando proyecto en sonar

diff --git a/.github/workflows/config.yml b/.github/workflows/config.yml
--- a/.github/workflows/config.yml
+++ b/.github/workflows/config.yml
@@ -5,42 +5,25 @@ on:
       - feature/lab_final
 
 jobs:
-  build:
+  SAST:
     runs-on: ubuntu-latest
     steps:
       
-      - name: Use Node.js 16.x
-        uses: actions/setup-node@v3
-        with:
-          node-version: '16.x'
-
-      - name: Set up JDK 17
+      - name: Configurar JDK 17
         uses: actions/setup-java@v2
         with:
             java-version: '17'
             distribution: 'adopt'
       
-      - name: Checkout Code
+      - name: Obtener Codigo
         uses: actions/checkout@v4
 
-      - name: Install Dependencies
+      - name: Validate existencia de SonarCloud para instalar en proyecto
         run: |
-          npm install
-          if [ $? -ne 0 ]; then
-            echo "Error al construir el proyecto"
-            # bash./.github/workflows/send-email.sh "Error Install Dependencies" "Se produjo un error en la instalación de dependencias en ${REPO_GITHUB}."
-            exit 1
-           else
-             echo "Instalación correcta"
-            #  bash./.github/workflows/send-email.sh "Instalació Correcta" "La instación de dependencias fue ejecutada exitosamente en ${REPO_GITHUB}."
-          fi
-
-      - name: Validate SonarCloud
-        run: |
-          if [ ! -d ~/.sonar ]; then
+          if [ ! -d ~/.sonar ] 
+          then
             echo "Dependencias de SonarCloud no encontradas. Instalando..."
             curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=labfinal-devsecops' -d 'visibility=public'
-            echo "Instalando..."
             if [ $? -ne 0 ]; then
               echo "Error al instalar SonarCloud"
               # bash./.github/workflows/send-email.sh "Error SonarCloud" "Se produjo un error en la instalación de SonarCloud en ${REPO_GITHUB}."
@@ -51,8 +34,50 @@ jobs:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: https://sonarcloud.io
 
-      - name: Build
-        run: npm run build
+      - name: Validar existencia del proyecto en SonarCloud
+        id: validarProyectoEnSonar
+        run: |
+          set +e
+          curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=labfinal-devsecops' -d 'visibility=public'
+          if [ $? -ne 0 ]
+          then
+            echo "Proyecto ya existe en SonarCloud"
+            # bash./.github/workflows/send-email.sh "Error SonarCloud" "Se produjo un error en la instalación de SonarCloud en ${REPO_GITHUB}."
+             exit 1
+          else
+            echo "Proyecto ${{ github.event.repository.name }} creado exitosamente"
+
+            echo "Se establece rama main como rama por defecto"
+            curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' '-d name=main' -d 'name=${{ github.event.repository.name }}'
+          fi
 
       - name: Mensaje de finalización
-        run: echo "Termino bien hasta ahora"
+        run: echo "Termino Job "
+
+
+  build:
+    runs-on: ubuntu-latest
+    steps:
+
+      - name: Configurar Node.js 16.x
+        uses: actions/setup-node@v3
+        with:
+          node-version: '16.x'
+
+      - name: Obtener Codigo
+        uses: actions/checkout@v4
+
+      - name: Instalar Dependencias
+        run: |
+          npm install
+          if [ $? -ne 0 ]; then
+            echo "Error al instalar dependencias"
+            # bash./.github/workflows/send-email.sh "Error Install Dependencies" "Se produjo un error en la instalación de dependencias en ${REPO_GITHUB}."
+            exit 1
+           else
+             echo "Instalación correcta"
+            #  bash./.github/workflows/send-email.sh "Instalació Correcta" "La instación de dependencias fue ejecutada exitosamente en ${REPO_GITHUB}."
+          fi
+
+      - name: Build
+        run: npm run build
