Se agrega notificación de correo para errores

diff --git a/.github/workflows/config.yml b/.github/workflows/config.yml
--- a/.github/workflows/config.yml
+++ b/.github/workflows/config.yml
@@ -9,15 +9,31 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-        # with:
-        #   sparse-checkout: .
+
       - name: Use Node.js 16.x
         uses: actions/setup-node@v3
         with:
           node-version: '16.x'
       
       - name: Install Dependencies
-        run: npm install  
+        run: |
+          npm install
+            if [ $? -ne 0 ]; then
+              echo "Error al construir el proyecto"
+              exit 1
+            fi
+      - name: print de repo
+        run: echo "perro pepe de la suerte -> ${GITHUB_REPO}"
+      
+      - name: Send Error Email - Install Dependencies
+        if: failure()
+        uses: actions/send-email@v1
+        with:
+          from: "github-actions@${GITHUB_REPO}.com"
+          to: ${{ secrets.EMAIL_RECIPIENT }}
+          subject: "Error en Install Dependencies"
+          body: "Se produjo un error en la instalación de dependencias en ${GITHUB_REPO}."
+
 
       - name: Validar existecia de SonarCloud
         run: |
@@ -29,6 +45,15 @@ jobs:
           else
             echo "Dependencias de SonarCloud encontradas."
           fi
+      
+      - name: Send Error Email - SonarCloud
+        if: failure()
+        uses: actions/send-email@v1
+        with:
+            from: "github-actions@${GITHUB_REPO}.com"
+            to: ${{ secrets.EMAIL_RECIPIENT }}
+            subject: "Error en prueba SAST"
+            body: "Se produjo un error en la verificación de existencia de SonarCloud en ${GITHUB_REPO}."
         
       # - name: SonarCloud Scan #SAST
       #   uses: sonarcloud/sonarcloud-github-action@v3
