Análisis SCA

diff --git a/.github/workflows/config.yml b/.github/workflows/config.yml
--- a/.github/workflows/config.yml
+++ b/.github/workflows/config.yml
@@ -5,72 +5,88 @@ on:
       - feature/lab_final
 
 jobs:
-  # SAST:
-  #   runs-on: ubuntu-latest
-  #   steps:
+  SAST:
+    runs-on: ubuntu-latest
+    steps:
       
-  #     - name: Configurar JDK 17
-  #       uses: actions/setup-java@v2
-  #       with:
-  #           java-version: '17'
-  #           distribution: 'adopt'
+      - name: Configurar JDK 17
+        uses: actions/setup-java@v2
+        with:
+            java-version: '17'
+            distribution: 'adopt'
       
-  #     - name: Obtener Codigo
-  #       uses: actions/checkout@v4
+      - name: Obtener Codigo
+        uses: actions/checkout@v4
 
-  #     - name: Validar existencia del proyecto en SonarCloud
-  #       id: validarProyectoEnSonar
-  #       run: |
-  #         set +e
-  #         curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=labfinal-devsecops' -d 'visibility=public'
-  #         if [ $? -ne 0 ]
-  #         then
-  #           echo "Proyecto ya existe en SonarCloud"
-  #           # bash./.github/workflows/send-email.sh "Error SonarCloud" "Se produjo un error en la instalación de SonarCloud en ${REPO_GITHUB}."
-  #         else
-  #           echo "Proyecto ${{ github.event.repository.name }} creado exitosamente"
+      - name: Validar existencia del proyecto en SonarCloud
+        id: validarProyectoEnSonar
+        run: |
+          set +e
+          curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=labfinal-devsecops' -d 'visibility=public'
+          if [ $? -ne 0 ]
+          then
+            echo "Proyecto ya existe en SonarCloud"
+            # bash./.github/workflows/send-email.sh "Error SonarCloud" "Se produjo un error en la instalación de SonarCloud en ${REPO_GITHUB}."
+          else
+            echo "Proyecto ${{ github.event.repository.name }} creado exitosamente"
 
-  #           echo "Se establece rama main como rama por defecto"
-  #           curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' '-d name=main' -d 'name=${{ github.event.repository.name }}'
-  #         fi
+            echo "Se establece rama main como rama por defecto"
+            curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' '-d name=main' -d 'name=${{ github.event.repository.name }}'
+          fi
 
-  #     - name: Instalar Sonar Scanner
-  #       id: InstallSonarScan
-  #       run: |
-  #         npm install -g sonar-scanner
+      - name: Instalar Sonar Scanner
+        id: InstallSonarScan
+        run: |
+          npm install -g sonar-scanner
 
-  #     - name: Análisis SonarCloud
-  #       if: steps.InstallSonarScan.outcome == 'success' 
-  #       env:
-  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-  #       run: |
-  #         sonar-scanner \
-  #           -Dsonar.projectKey=${{ github.event.repository.name }} \
-  #           -Dsonar.organization=labfinal-devsecops \
-  #           -Dsonar.host.url=https://sonarcloud.io \
-  #           -Dsonar.login=$SONAR_TOKEN \
-  #           -Dsonar.branch.name=feature/lab_final \
-  #           -Dsonar.sources=. \
-  #           -Dsonar.language=js \
-  #           -Dsonar.sourceEncoding=UTF-8 \
-  #           -Dsonar.exclusions=**/node_modules/** \
-  #           -Dsonar.inclusions=**/*.js,**/*.jsx,**/*.ts,**/*.tsx \
-  #           -Dsonar.qualitygate.wait=true
+      - name: Análisis SonarCloud
+        if: steps.InstallSonarScan.outcome == 'success' 
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: |
+          sonar-scanner \
+            -Dsonar.projectKey=${{ github.event.repository.name }} \
+            -Dsonar.organization=labfinal-devsecops \
+            -Dsonar.host.url=https://sonarcloud.io \
+            -Dsonar.login=$SONAR_TOKEN \
+            -Dsonar.branch.name=feature/lab_final \
+            -Dsonar.sources=. \
+            -Dsonar.language=js \
+            -Dsonar.sourceEncoding=UTF-8 \
+            -Dsonar.exclusions=**/node_modules/** \
+            -Dsonar.inclusions=**/*.js,**/*.jsx,**/*.ts,**/*.tsx \
+            # -Dsonar.qualitygate.wait=true
 
-  #     - name: Mensaje de finalización
-  #       run: echo "Termino Job "
+      - name: Mensaje de finalización
+        run: echo "Termino Job "
 
   CSA:
+    needs: SAST
     runs-on: ubuntu-latest
     steps:
       - name: Obtener Codigo
         uses: actions/checkout@v4
 
-      - name: Instalar DependencyCheck
-        run: |
-          curl -sSf https://dependency-check.org/install.sh | sh
+      # - name: Instalar DependencyCheck
+      #   run: |
+      #     curl -sSf https://dependency-check.org/install.sh | sh
 
-      - name: Análsis SCA
-        uses: dependency-check/dependency-check-github-action@v1
+      - name: Análisis SCA
+        uses: dependency-check/Dependency-Check_Action@1.1.0
+        env:
+          JAVA_HOME: /opt/jdk
+        id: Depcheck
         with:
-          args: --scanSet --format XML --out report.xml.
+          project: '${{ github.event.repository.name }}'
+          path: '.'
+          format: 'HTML'
+          out: 'report'
+          args: >
+            --failOnCVSS 7
+            --enableRetired
+
+      - name: Upload resultado
+        uses: actions/upload-artifacts@master
+        with:
+          name: Depcheck report
+          path: ${{github.workflow}}/report
