Se comenta Codigo, para la validación de existencia del proyecto en sonar

diff --git a/.github/workflows/config.yml b/.github/workflows/config.yml
--- a/.github/workflows/config.yml
+++ b/.github/workflows/config.yml
@@ -18,21 +18,21 @@ jobs:
       - name: Obtener Codigo
         uses: actions/checkout@v4
 
-      - name: Validate existencia de SonarCloud para instalar en proyecto
-        run: |
-          if [ ! -d ~/.sonar ] 
-          then
-            echo "Dependencias de SonarCloud no encontradas. Instalando..."
-            curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=labfinal-devsecops' -d 'visibility=public'
-            if [ $? -ne 0 ]; then
-              echo "Error al instalar SonarCloud"
-              # bash./.github/workflows/send-email.sh "Error SonarCloud" "Se produjo un error en la instalación de SonarCloud en ${REPO_GITHUB}."
-              exit 1
-            fi
-          fi
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          SONAR_HOST_URL: https://sonarcloud.io
+      # - name: Validando existencia de proyecto en SonarCloud
+      #   run: |
+      #     if [ ! -d ~/.sonar ] 
+      #     then
+      #       echo "Dependencias de SonarCloud no encontradas. Instalando..."
+      #       curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=labfinal-devsecops' -d 'visibility=public'
+      #       if [ $? -ne 0 ]; then
+      #         echo "Error al instalar SonarCloud"
+      #         # bash./.github/workflows/send-email.sh "Error SonarCloud" "Se produjo un error en la instalación de SonarCloud en ${REPO_GITHUB}."
+      #         exit 1
+      #       fi
+      #     fi
+      #   env:
+      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      #     #SONAR_HOST_URL: https://sonarcloud.io
 
       - name: Validar existencia del proyecto en SonarCloud
         id: validarProyectoEnSonar
@@ -43,12 +43,11 @@ jobs:
           then
             echo "Proyecto ya existe en SonarCloud"
             # bash./.github/workflows/send-email.sh "Error SonarCloud" "Se produjo un error en la instalación de SonarCloud en ${REPO_GITHUB}."
-             exit 1
           else
             echo "Proyecto ${{ github.event.repository.name }} creado exitosamente"
 
             echo "Se establece rama main como rama por defecto"
-            curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' '-d name=main' -d 'name=${{ github.event.repository.name }}'
+            curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' '-d name=main' -d 'name=${{ github.event.repository.name }}'
           fi
 
       - name: Mensaje de finalización
