Se reempalzan nombres y se agregan mensajes de error y/o exito en SAST

diff --git a/.github/workflows/config.yml b/.github/workflows/config.yml
--- a/.github/workflows/config.yml
+++ b/.github/workflows/config.yml
@@ -9,21 +9,21 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       
-      - name: Configurar JDK 17
+      - name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
             java-version: '17'
             distribution: 'adopt'
       
-      - name: Obtener Codigo
+      - name: Checkoutr Code
         uses: actions/checkout@v4
 
-      - name: Validar existencia del proyecto en SonarCloud
-        id: validarProyectoEnSonar
+      - name: Validate existence of the project in SonarCloud
+        #id: ValidateProjectInSonar
         run: |
-          set +e
-          curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=labfinal-devsecops' -d 'visibility=public'
-          if [ $? -ne 0 ]
+          set -e
+          response=$(curl -s -o /dev/null -w "%{http_code}" -u '${{ secrets.SONAR_TOKEN }}:' "https://sonarcloud.io/api/projects/create?name=${{ github.event.repository.name }}&project=${{ github.event.repository.name }}&organization=labfinal-devsecops&visibility=public")
+          if [ "$response" -ne "201" ]
           then
             echo "Proyecto ya existe en SonarCloud"
             # bash./.github/workflows/send-email.sh "Error SonarCloud" "Se produjo un error en la instalación de SonarCloud en ${REPO_GITHUB}."
@@ -34,12 +34,17 @@ jobs:
             curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' '-d name=main' -d 'name=${{ github.event.repository.name }}'
           fi
 
-      - name: Instalar Sonar Scanner
+      - name: Install Sonar Scann
         id: InstallSonarScan
         run: |
-          npm install -g sonar-scanner
+           npm install -g sonar-scanner
+           if [ $? -ne 0 ]
+           then
+            echo "Error al instalar Sonar Scanner"
+            exit 1
+           fi
 
-      - name: Análisis SonarCloud
+      - name: SonarCloud Analysis
         if: steps.InstallSonarScan.outcome == 'success' 
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
@@ -56,9 +61,14 @@ jobs:
             -Dsonar.exclusions=**/node_modules/** \
             -Dsonar.inclusions=**/*.js,**/*.jsx,**/*.ts,**/*.tsx \
             # -Dsonar.qualitygate.wait=true
+          if [ $? -ne 0 ]
+          then
+            echo "Error al ejecutar SonarCloud"
+            exit 1
+          fi
 
-      - name: Mensaje de finalización
-        run: echo "Termino Job "
+      - name: Finish Job
+        run: echo "Termino del Job "
 
   CSA:
     needs: SAST
